version: '3'

services:
  busybox:
    image: nginx
    labels:
      - "bugloos.supervisor.program_name=test"
      - "bugloos.supervisor.command=/bin/ls"

  supervisord:
    build:
      context: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
